### ISSUE TITLE
Discrepancy in usage of presenter_for_path and presenter_for_name

### ISSUE THREAD

**Issue by jeremyf** [zendesk/curly#147]
Consider the following, when we call a `presenter_for_path` we allow for nil to be returned. When we call `presenter_for_name`, nil is not an option instead we raise `Curly::PresenterNameError`. The following line seems redundant, given that we can change `presenter_for_path` to bubble up with a `PresenterNameError` (or `PresenterNotFound` in both cases).

I don't know if these methods are considered part of the public API, but it is something to consider.

```ruby
presenter_class = Curly::Presenter.presenter_for_path(path)

raise Curly::PresenterNotFound.new(path) if presenter_class.nil?
```
https://github.com/zendesk/curly/blob/master/lib/curly/template_handler.rb#L48-L50

```ruby
def presenter_for_path(path)
  begin
    presenter_for_name(path.camelize, [])
  rescue Curly::PresenterNameError
    nil
  end
end
```
https://github.com/zendesk/curly/blob/master/lib/curly/presenter.rb#L158-L166

**Comment by dasch** [comment]
It's a public API, so it may break clients that use those methods :-/

**Comment by jeremyf** [comment]
So, any pull request would necessitate a major version bump? A deprecation strategy?

**Comment by dasch** [comment]
Yeah, stuff like that. It's typically not worth it.

**Comment by jeremyf** [comment]
@dasch I yield to you regarding what you want to do? Close the issue or keep it open and say "help wanted"

**Comment by dasch** [comment]
I'd rather close this – it doesn't seem like a huge problem, and API stability is more important.
