### ISSUE TITLE
How to test a presenter?

### ISSUE THREAD

**Issue by diegotoral** [zendesk/curly#148]
Hi folks!

I'm trying to test (with RSpec) a simple presenter class that uses a bunch of helper methods (`button_to`, `t` and `sign_out_url`) and I don't know how to setup the presenter in a way it access these methods.

```ruby
class Dashboard::IndexPresenter < Curly::Presenter
  def sign_out
    button_to t('layouts.application.sign_out'), sign_out_url, method: :delete
  end
end
```

Thanks!

**Comment by dasch** [comment]
Typically, you'd include [RSpec::Rails::ViewExampleGroup](https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/example/view_example_group.rb) into your spec:

```ruby
describe Dashboard::IndexPresenter do
  include RSpec::Rails::ViewExampleGroup
  let(presenter) { described_class.new(view, view_assigns) }
end
```

Let me know if that works for you.

**Comment by diegotoral** [comment]
That worked for me! Thanks for the answer @dasch!

**Comment by dasch** [comment]
No problem :-)

**Comment by dasch** [comment]
@diegotoral I'm adding directly RSpec support in the next Curly release: #149.
