### ISSUE TITLE
rendering curly templates in controllers

### ISSUE THREAD

**Issue by aydoganozturk** [zendesk/curly#162]
In rails, we can render json, html partials or views with render_to_string. But, could not figure out, how to render same way for curly template code which is stored in database table. Let's say, we have post model and template model. Template model has code column which handles curly code. Now, we want to render this curly code and send last html code in email as attachment. Is it possible ?

```
def preview
  @post = Post.find(params[:id])
  template = Template.find(params[:template_id])
  prepend_view_path CustomTemplateResolver.new

  tempdoc_html = Curly::Compiler.compile(template.code, Post::PreviewPresenter)   
  temp_html_str = render_to_string(tempdoc_html)  # This line gets error, we will send temp_html_str as email attachment.
end
```

**Comment by dasch** [comment]
Have you looked at https://github.com/zendesk/curly/wiki/Storing-templates-in-the-database?

Out of curiosity, what errors are you seeing?
